const STATUS_RESPONSE = {
  ERROR: 'error',
  SUCCESS: 'success',
  FAILED: 'failed',
};
let SIGNUP_STATUS = ``;
let SIGNUP_QUERY = ``;
let SIGNIN_QUERY = ``;
let GET_ALL_USER_DATA_QUERY = ``;
let DELETE_USER_DATA_QUERY = ``;

module.exports = {
  STATUS_RESPONSE,
  SIGNUP_STATUS,
  SIGNUP_QUERY,
  SIGNIN_QUERY,
  GET_ALL_USER_DATA_QUERY,
  DELETE_USER_DATA_QUERY,
};
